### ISSUE TITLE
can't back out of feedback menu

### ISSUE THREAD

**Issue by modgethanc** [modgethanc/ttbp#39]
on the 'send feedback' menu, typing 'q' doesn't take you back to the main screen like all the other menus.

**Comment by hyperreal64** [comment]
For what it's worth: I've found that pressing CTRL-C takes you back to the main menu.

I also believe the following code fixes this bug appropriately:

```python
def feedback_menu():
    """
    feedback handling menu

    * selects feedback type
    * calls feedback writing function
    """

    util.print_menu(SUBJECTS, SETTINGS.get("rainbows", False))
    choice = input("\npick a category for your feedback (or type 'q' to exit): ")

    cat = ""
    if choice in ["0", "1", "2", "3"]:
        cat = SUBJECTS[int(choice)]
        entered = input(
            """
composing a {mail_category} to ~endorphant.

press <enter> to open an external text editor. mail will be sent once you save and quit.

""".format(
                mail_category=cat
            )
        )
        redraw(send_feedback(entered, cat))
        return
    elif choice in QUITS:
        return stop()
    else:
        redraw(INVALID)

    return feedback_menu()
```

I'd make a pull request but I'm not sure how to build this code locally to test the above changes. `python3 setup.py install` is deprecated. I've tried `pipx install .` in the root of this repository, which installed the `feels` binary to `~/.local/bin/feels`. However, running that binary gives the following error:
```
Traceback (most recent call last):
  File "/home/jas/.local/bin/feels", line 5, in <module>
    from ttbp.ttbp import main
  File "/home/jas/.local/pipx/venvs/ttbp/lib/python3.11/site-packages/ttbp/ttbp.py", line 48, in <module>
    from . import config
ImportError: cannot import name 'config' from 'ttbp' (/home/jas/.local/pipx/venvs/ttbp/lib/python3.11/site-packages/ttbp/__init__.py)
```
