### ISSUE TITLE
Exception: bad system state: /var/global does not exist.

### ISSUE THREAD

**Issue by decentral1se** [modgethanc/ttbp#44]
r a d project! tried to install (`pip install .`) with https://github.com/modgethanc/ttbp/pull/41 merged in and saw this:

```
Traceback (most recent call last):
  File "/home/d/ttbp/.venv/bin/feels", line 11, in <module>
    load_entry_point('ttbp==0.12.2', 'console_scripts', 'feels')()
  File "/home/d/ttbp/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/d/ttbp/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/home/d/ttbp/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/d/ttbp/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/d/ttbp/.venv/lib/python3.7/site-packages/ttbp/ttbp.py", line 48, in <module>
    from ttbp import config, core, chatter, gopher, util
  File "/home/d/ttbp/.venv/lib/python3.7/site-packages/ttbp/config/__init__.py", line 19, in <module>
    raise Exception('bad system state: /var/global does not exist.')
Exception: bad system state: /var/global does not exist.
```

Not really sure how to fix that :thinking:

**Comment by decentral1se** [comment]
Ah, just had to `mkdir /var/global`!
